--
-- ClinVar phenotypes
--

drop table if exists clinvar_phenotypes;

create table clinvar_phenotypes (
    id smallint not null,
    description varchar(150) not null,
    genes_info varchar(450) not null,
    primary key(id)
);

-- this file is generated by jupyter notebook 200_webapp/generate_ukb_clinvar_table.ipynb
\copy clinvar_phenotypes from /mnt/phenomexcan_base/webapp/ukb_clinvar-clinvar_traits.tsv with delimiter as E'\t' csv header;

CREATE INDEX cp_description_idx ON clinvar_phenotypes (description);
