drop table if exists ukb_clinvar;

create table ukb_clinvar (
    ukb_pheno_id smallint not null REFERENCES phenotypes,
    clinvar_pheno_id smallint not null REFERENCES clinvar_phenotypes,
    sqrt_z2_avg real not null,
    primary key(ukb_pheno_id, clinvar_pheno_id)
);

-- this file is generated by jupyter notebook 200_webapp/generate_ukb_clinvar_table.ipynb
\copy ukb_clinvar from /mnt/phenomexcan_base/gene_assoc/ukb_clinvar.tsv with delimiter as E'\t' csv header;

CREATE INDEX uc_sqrt_z2_avg_idx ON ukb_clinvar (sqrt_z2_avg DESC);
CREATE INDEX uc_ukb_trait_z2_idx ON ukb_clinvar (ukb_pheno_id, sqrt_z2_avg DESC);
CREATE INDEX uc_clinvar_trait_z2_idx ON ukb_clinvar (clinvar_pheno_id, sqrt_z2_avg DESC);
CREATE INDEX uc_ukb_trait_clinvar_trait_z2_idx ON ukb_clinvar (ukb_pheno_id, clinvar_pheno_id, sqrt_z2_avg DESC);
