drop table if exists tissues;

create table tissues (
    id smallint not null,
    name varchar(40) not null,
    primary key(id)
);

-- the file here is the uncompressed version of the file generated by the jupyter
-- notebook 100_postprocessing/01_genes_mappings.ipynb
\copy tissues from /mnt/phenomexcan_base/deliverables/tissues.tsv with delimiter as E'\t' csv header;

CREATE INDEX t_name_idx ON tissues (name);
