--
-- UKB phenotypes
--

drop table if exists ukb_clinvar_ukb_pheno_info;

create table ukb_clinvar_ukb_pheno_info (
    pheno_desc varchar(225) not null,
    primary key(pheno_desc)
);

-- this file is generated by jupyter notebook 200_webapp/generate_ukb_clinvar_table.ipynb
\copy ukb_clinvar_ukb_pheno_info from /mnt/phenomexcan_base/webapp/ukb_clinvar-ukb_traits.tsv with delimiter as E'\t' csv header;

--
-- ClinVar phenotypes
--

drop table if exists ukb_clinvar_clinvar_pheno_info;

create table ukb_clinvar_clinvar_pheno_info (
    pheno_desc varchar(150) not null,
    primary key(pheno_desc)
);

-- this file is generated by jupyter notebook 200_webapp/generate_ukb_clinvar_table.ipynb
\copy ukb_clinvar_clinvar_pheno_info from /mnt/phenomexcan_base/webapp/ukb_clinvar-clinvar_traits.tsv with delimiter as E'\t' csv header;
