channels:
  - defaults
dependencies:
  - ipython=7.6
  - jupyter=1.0.0
  - jupyterlab=1.2
  - json5=0.8.5
  - matplotlib=3.1
  - numpy=1.16
  - pandas=0.24
  - patsy=0.5
  - pip=19.1
  - python=3.7
  - r-essentials=3.6
  - rpy2=2.9
  - scikit-learn=0.21
  - scipy=1.3
  - seaborn=0.9
  - statsmodels=0.10
  - xlrd=1.2
  - xlwt=1.3
  - postgresql=11.2
  - pytables=3.6
  - openpyxl=3.0
  - tzlocal=2.0
  - wget=1.20
  - pip:
    - papermill==1.2.1
